[tool.black]
line-length = 100
target-version = ['py39']

[tool.isort]
profile = 'black'
src_paths = ['tests', 'config']
line_length = 100

[tool.pytest.ini_options]
testpaths = ['tests', 'config']
addopts = '--doctest-modules --cov=config --cov-report html:coverage --cov-report=term-missing --durations=10'
